name: 'Next Version'
description: 'Compute next semantic version using semantic-release dry-run'
author: 'Markus Windhager'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  branches:
    description: 'Branch rule specs (one per line). Format: "<name>[;key[=value]]..." e.g. "main", "develop;prerelease=dev;channel=develop"'
    required: true
  tag-format:
    description: 'Git tag format (default: "v${version}")'
    required: false
  preset:
    description: 'Conventional changelog preset (default: "angular")'
    required: false
    default: 'angular'

outputs:
  version:
    description: 'The computed next version (e.g. 1.2.3 or 1.2.3-dev.4)'
  channel:
    description: 'Release channel (e.g. latest, develop, beta)'
  type:
    description: 'Release type (major, minor, patch)'
  git-tag:
    description: 'The git tag for this release'
  git-head:
    description: 'The git commit SHA'
  name:
    description: 'Release name'

runs:
  using: 'node20'
  main: 'bin/action.js'
